Add the updated files for the github actions learning

diff --git a/github-actions-learning/course/lessons/04-advanced-features--08-workflow-commands.yaml b/github-actions-learning/course/lessons/04-advanced-features--08-workflow-commands.yaml
--- a/github-actions-learning/course/lessons/04-advanced-features--08-workflow-commands.yaml
+++ b/github-actions-learning/course/lessons/04-advanced-features--08-workflow-commands.yaml
@@ -13,36 +13,42 @@ jobs:
 
       - name: Log annotations
         run: |
-          # Debug output (visible only when repo secret ACTIONS_STEP_DEBUG=true)
+          # Debug output (visible only when the repo secret is set to true => ACTIONS_STEP_DEBUG=true)
           echo "::debug::Step started - hello from debug"
 
-          file=".github/workflows/04-advanced-features--07-workflow-commands.yaml"
+          file=".github/workflows/04-advanced-features--08-workflow-commands.yaml"
+          
+          # Make sure not to add any spaces here between the parameters
           echo "::notice file=$file,line=23::By specifying a line (and optionally a column) the notice is linked to the source file"
 
           echo "::warning title=Some Warning::A more detailed description of the warning"
 
-          # Fails the run visually, but does **not** stop execution (you should `exit 1` to stop execution)
+          # Fails the run visually, but does not stop execution (you should run "exit 1" to stop execution)
           echo "::error title=Some Error::A more detailed description of the error"
 
       - name: Grouped logs
         run: |
           echo "::group::This is a group of logs"
-          echo "Hello from within the group! 👋"
+          echo "Hello from within the group!"
           echo "::endgroup::"
 
       - name: Mask a value
         env:
-          FOO: "bar"
+          SECRET: "secret-value"
         run: |
-          echo "::add-mask::$FOO"
-          echo "FOO is $FOO" # This will print *** instead of "bar"
+          echo "::add-mask::$SECRET"
+
+          # This will print *** instead of "secret-value"
+          echo "SECRET is $SECRET"
 
       - name: Stop & resume workflow commands
         run: |
-          marker=$(uuidgen)
+          marker=$(uuidgen) # available on Ubuntu, so keep in mind if changing OS
           echo "::stop-commands::$marker"
-          echo "::error::This is *not* rendered as an error"
-          echo "::$marker::" # resume processing
+          echo "::error::This is not rendered as an error"
+
+          # resume processing
+          echo "::$marker::"
           echo "::notice::Processing resumed"
 
       - name: Set an environment variable
@@ -54,16 +60,16 @@ jobs:
 
       - name: Append to step summary
         run: |
-          echo "### Build completed 🚀" >> $GITHUB_STEP_SUMMARY
+          echo "### Build completed" >> $GITHUB_STEP_SUMMARY
           echo "- Build ID: $BUILD_ID" >> $GITHUB_STEP_SUMMARY
-          echo "- Colour : ${{ steps.pick-color.outputs.choice }}" >> $GITHUB_STEP_SUMMARY
+          echo "- Color : ${{ steps.pick-color.outputs.choice }}" >> $GITHUB_STEP_SUMMARY
 
       - name: Add custom path
         run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"
 
       - name: Use env, output, and PATH
         env:
-          CHOSEN_COLOUR: ${{ steps.pick-color.outputs.CHOICE }}
+          CHOSEN_COLOUR: ${{ steps.pick-color.outputs.choice }}
         run: |
           echo "Current PATH is:"
           echo "$PATH"
